### ISSUE TITLE
what is the difference between ”Places365“ and ”PLACES“？

### ISSUE THREAD

**Issue by adaxigua** [gist-ailab/block-selection-for-OOD-detection#1]
In the paper, page 4

> We use SVHN [34], Textures [2], LSUN-crop [56](LSUN(c)), LSUN-resize [56](LSUN(r)), iSUN [53], and **Places365** [59] as OOD datasets for CIFAR10 benchmark. We use iNaturalist [49], SUN [51], **PLACES** [59], and Textures [2], which are sampled by Huang et al. [18], as OOD dataset For the ImageNet benchmark

What is the difference between ”Places365“ and ”PLACES“？Are they the same datasets? Thanks!

**Comment by birdomi** [comment]
They are sampled from the same dataset, but there is a small difference.

- Places365: 10,000 images which are randomly sampled from the test dataset as in https://github.com/wetliu/energy_ood.
- PLACES: 10,000 images which are manually sampled from the test dataset to remove overlapped images with ImageNet categories. The images are provided in https://github.com/deeplearning-wisc/large_scale_ood.

I hope this comment helps you.
