### ISSUE TITLE
How to generate Jigsaw puzzle images

### ISSUE THREAD

**Issue by yjnanan** [gist-ailab/block-selection-for-OOD-detection#3]
Hello, I appreciate your work, could you please tell me how to generate Jigsaw puzzle images? I did't find it in your released code. Thanks!

**Comment by birdomi** [comment]
Apologies for your inconvenience. 
I released the incorrect code. I have now updated the code, and you can find the 3x3 jigsaw puzzle generation code in "utils/dataset.py".
