### ISSUE TITLE
Question about  Code for  resnet50, vgg16, and MobileNetV3

### ISSUE THREAD

**Issue by Gidear** [gist-ailab/block-selection-for-OOD-detection#5]
Hi，author！
Thank you for your outstanding contribution! Recently, I want to learn more about your work by running the code. 
May I ask if you could upload the resnet50, vgg16, and MobileNetV3 code for reproducing ImageNet? I would greatly appreciate it for this.
Thanks！

**Comment by birdomi** [comment]
Thank you for your attention in our work.

We upload the evaluation code for ImageNet with those architectures. 

For the usage, you have to download the ImageNet data in "../data/imagenet" as default setting of ImageNet.json.
Also, download the iNaturalist, SUN, Places, Textures dataset for evaluation and place it in the same folder. (e.g., './OOD_for_ImageNet/' as default setting).
You may download the datasets in https://github.com/deeplearning-wisc/react.
